# Generated by Django 5.0.3 on 2024-03-28 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="date_added",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 3, 28, 21, 11, 14, 592769, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
