# Generated by Django 5.0.3 on 2024-03-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
