# Generated by Django 5.0.3 on 2024-04-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
